server:
  port: 8089
  tomcat:
    uri-encoding: UTF-8

spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:10001/wanhao?useUnicode=true;characterEncoding=UTF-8;autoReconnect=true;useSSL=false;zeroDateTimeBehavior=convertToNull
    username: root
    password: 123123
    type: com.zaxxer.hikari.HikariDataSource
    hikari:
      maximum-pool-size: 1000
      minimum-idle: 5
      auto-commit: true
      idle-timeout: 30000
      pool-name: DatebookHikariCP
      max-lifetime: 1800000
      connection-timeout: 30000
      connection-test-query: SELECT 1

  jpa:
    database: mysql
    show-sql: true
    hibernate:
      ddl-auto: update
      naming-strategy: org.hibernate.cfg.ImprovedNamingStrategy